name: Ubuntu 22.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Checkout andy-lang
      uses: actions/checkout@v3
      with:
        path: 'andy-lang'

    - name: Configure CMake for andy-lang
      run: cmake -DCLONE_AND_INCLUDE_DEPENDENCIES=ON -B build .
      working-directory: andy-lang
      
    - name: Build project for andy-lang
      run: cmake --build build --config Release --parallel --target andy
      working-directory: andy-lang

    - name: Install andy-lang
      run: sudo cmake --install build --config Release --component andy
      working-directory: andy-lang

    - name: Check andy-lang version
      run: andy --version
      working-directory: andy-lang