name: Windows Server 2022

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout andy-lang
      uses: actions/checkout@v3
      with:
        path: 'andy-lang'

    - name: Configure CMake for andy-lang
      run: cmake -DCLONE_AND_INCLUDE_DEPENDENCIES=ON -B build .
      working-directory: andy-lang
      
    - name: Build project for andy-lang
      run: cmake --build build --config Release --parallel
      working-directory: andy-lang

    - name: Install andy-lang
      run: cmake --install build --config Release
      working-directory: andy-lang