name: Ubuntu 18.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - name: Checkout andy-lang
      uses: actions/checkout@v3
      with:
        path: 'andy-lang'
        submodules: 'recursive'

    - name: Build Docker image
      run: docker build -t andy-lang:latest .
      working-directory: andy-lang

    - name: Run Docker container
      run: docker run -v $(pwd)/andy-build:/andy-build andy-lang:latest
      working-directory: andy-lang

    - name: Generate artifacts
      uses: actions/upload-artifact@v4
      with:
        name: andy
        path: |
          andy-lang/andy-build/build/andy
          andy-lang/andy-build/build/andy-analyzer

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: andy-lang/andy-build/andy_tests.xml

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: andy-build/andy_tests.xml
        reporter: java-junit
        working-directory: andy-lang

    - name: Run andy-pkgr
      run: build/andy-pkgr
      working-directory: andy-lang

    - name: Get andy-lang version
      id: get_version
      run: |
        VERSION=$(build/andy --version)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      working-directory: andy-lang

    - name: Publish andy-lang version
      if: github.ref == 'refs/heads/master'
      env:
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: |
        curl -X PATCH "https://www.andy-lang.org/api/v1/packages/andy-lang/${{ steps.get_version.outputs.version }}" \
          -H "Email: $ADMIN_EMAIL" \
          -H "Password: $ADMIN_PASSWORD" \
          -F "executable=@andy-lang-${{ steps.get_version.outputs.version }}.deb" \
      working-directory: andy-lang