name: Windows Server 2022

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout uva
      uses: actions/checkout@v3
      with:
        repository: andrey-moura/uva
        submodules: recursive
        path: 'uva'
    
    - name: Checkout uvalang
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: 'uva-lang'
        
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build .
      working-directory: uva-lang
      
    - name: Build project
      run: cmake --build build --config Release --parallel
      working-directory: uva-lang