name: Ubuntu 20.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y build-essential
    
    - name: Checkout andy
      uses: actions/checkout@v3
      with:
        repository: andrey-moura/andy
        path: 'andy'
    
    - name: Checkout andylang
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: 'andy-lang'
        
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build .
      working-directory: andy-lang
      
    - name: Build project
      run: cmake --build build --config Release --parallel
      working-directory: andy-lang
