name: Ubuntu 18.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Checkout andy-lang
      uses: actions/checkout@v3
      with:
        path: 'andy-lang'
        submodules: 'recursive'

    - name: Build Docker image
      run: docker build -t andy-lang:latest .
      working-directory: andy-lang

    - name: Run Docker container
      run: docker run -v $(pwd)/andy-build:/andy-build andy-lang:latest
      working-directory: andy-lang
